# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Please do not change anything if you dont know what you are doing
siteIP: "172.17.177.89"

sites: |
  [ 'apim-dev.niseee.gov.bd', 'identity-dev.niseee.gov.bd']

postgresql:
  enabled: true
  global:
    postgresql:
      postgresqlDatabase: "usersdb"
      postgresqlPassword: "Hello@123"
      postgresqlUsername: "userservice-pguser"
      servicePort: "5432"

variables:
  apiServiceName: gauzy-demo-api
  apiServiceType: LoadBalancer
  apiServicePort: 80
  apiServiceTargetPort: 3000
  apiServicePortLts: 443
  APP_ENV: DEV
  API_ENV: DEV
  hostName: lsg.gov.bd

  # if values is false, then creating ingress will be escape
  enableEngress: true

  # ingress cluster-issuer class
  ingressClusterIssuer: "k-issuer"

  # is lts acme, value is boolean
  ltsAcme: false

  # app version, changing version will auto deploy the app to current version

  imageAppVersion: "latest"
  apiImageAppVersion: "latest"

  # increase this when you need scale up
  replicaCount: 1

  imagePullPolicy: IfNotPresent

  serviceType: LoadBalancer

  # service port, this provide traffic to ingress within this port
  servicePortLts: 443

  servicePort: 80

  # target container port
  serviceTargetPort: 4200

  #app buil image
  imageRepository: "everco/gauzy-webapp-demo"
  apiImageRepository: "everco/gauzy-api-demo"


  #auto scaling config
  #autoScalingEnabled: 0

  #autoScalingMinReplicas: 1

  #autoScalingMaxReplicas: 100

  #autoScalingTargetCPUUtilizationPercentage: 80

  #autoScalingTargetMemoryUtilizationPercentage: 80

  #control git realese branch
  API_DEV:
    GIT_DEVELOPMENT_BRANCH: "main"
    GIT_PRODUCTION_BRANCH: "master"
    API_HOST: 0.0.0.0
    DEMO: true
    NODE_ENV: development
    ADMIN_PASSWORD_RESET: true
    LOG_LEVEL: info
    SENTRY_DSN: 'https://7cd381188b6f446ca0e69185227b9031@o51327.ingest.sentry.io/4397292'
    SENTRY_HTTP_TRACING_ENABLED: false
    SENTRY_POSTGRES_TRACKING_ENABLED: false
    API_BASE_URL: 'https://apidemo.gauzy.co'
    CLIENT_BASE_URL: 'https://demo.gauzy.co'
    EXPRESS_SESSION_SECRET: gauzy
    JWT_SECRET: secretKey
    JWT_REFRESH_TOKEN_SECRET: refreshSecretKey
    JWT_REFRESH_TOKEN_EXPIRATION_TIME: '86400'

  DEV:
    APP_ENV: "DEV"
    DEMO: 'true'
    API_BASE_URL: 'https://apidemo.gauzy.co'
    CLIENT_BASE_URL: 'https://demo.gauzy.co'
    SENTRY_DSN: 'https://7cd381188b6f446ca0e69185227b9031@o51327.ingest.sentry.io/4397292'
    CHATWOOT_SDK_TOKEN: 'jFoSXEjGmqhUhqU3zfgkFfMt'
    CLOUDINARY_API_KEY: '256868982483961'
    CLOUDINARY_CLOUD_NAME: 'dv6ezkfxg'
    GOOGLE_MAPS_API_KEY: 'AIzaSyCJmnKzgTSq5Pc93HXar5bZrdmANTwtSIo'
    GOOGLE_PLACE_AUTOCOMPLETE: 'true'
    DEFAULT_LATITUDE: '42.6459136'
    DEFAULT_LONGITUDE: '23.3332736'
    DEFAULT_CURRENCY: 'USD'
    GAUZY_GITHUB_CLIENT_ID: '$GAUZY_GITHUB_CLIENT_ID'
    GAUZY_GITHUB_APP_NAME: '$GAUZY_GITHUB_APP_NAME'
    GAUZY_GITHUB_REDIRECT_URL: '$GAUZY_GITHUB_REDIRECT_URL'
    GAUZY_GITHUB_POST_INSTALL_URL: '$GAUZY_GITHUB_POST_INSTALL_URL'
    GAUZY_GITHUB_APP_ID: '$GAUZY_GITHUB_APP_ID'
    JITSU_BROWSER_URL: '$JITSU_BROWSER_URL'
    JITSU_BROWSER_WRITE_KEY: '$JITSU_BROWSER_WRITE_KEY'

#auto scaling config
autoScaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  # with this time if uses of resource up/down then do not autoscale down
  stabilizationWindowSecondsForScaleDown: 1200

resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
