apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.variables.apiServiceName }}
spec:
  type: {{ .Values.variables.apiServiceType }}
  selector:
    app: {{ .Values.variables.apiServiceName }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.variables.apiServicePort }}
      targetPort: {{ .Values.variables.apiServiceTargetPort }}
    - name: https
      protocol: TCP
      port: {{ .Values.variables.apiServicePortLts }}
      targetPort: {{ .Values.variables.apiServiceTargetPort }}

