apiVersion: v1
kind: Service
metadata:
  name: {{ include "ever-gauzy.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ever-gauzy.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      protocol: TCP
      port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.httpsPort }}
  selector:
    {{- include "ever-gauzy.selectorLabels" . | nindent 4 }}
